# Generated by Django 5.0.6 on 2024-06-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('post', '0002_auto_20240620_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(related_name='blog_post', to='post.post'),
        ),
    ]
